version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"